FROM python:3.13-alpine
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV ENV production

WORKDIR /cdn-service

RUN pip install --no-cache uv python-multipart

COPY . .
RUN uv sync

EXPOSE 8000
CMD [ "uv", "run", "gunicorn", "src.main:app", "--bind", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker" ]
